# Generated by Django 4.1.2 on 2022-11-05 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0003_hand_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
