# Generated by Django 4.1.2 on 2022-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0006_likedhand"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
