# Generated by Django 4.1.2 on 2022-11-13 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0008_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="description",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="photo",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photos")),
                ("description", models.CharField(max_length=250)),
                ("favorite_movie", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
