# Generated by Django 4.1.2 on 2022-11-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0009_remove_customuser_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorite_movie",
            field=models.IntegerField(blank=True),
        ),
    ]
