# Generated by Django 4.1.2 on 2022-11-15 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0011_alter_profile_favorite_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20),
                default=list,
                size=5,
            ),
        ),
    ]
