# Generated by Django 4.1.2 on 2022-11-15 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hands", "0012_alter_hand_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20, null=True),
                default=list,
                size=5,
            ),
        ),
    ]
